
// ============================================================
//  ÁLBUM DATA v2 — Mundial 2026
// ============================================================

const ALBUM_DATA = {

  // ── INTRO ────────────────────────────────────────────────
  intro: {
    label: 'Introducción',
    items: [
      { code:'FWC00', name:'Panini (portada especial)' },
      { code:'FWC1',  name:'Copa del Mundo — mitad superior' },
      { code:'FWC2',  name:'Copa del Mundo — mitad inferior' },
      { code:'FWC3',  name:'Mascotas' },
      { code:'FWC4',  name:'Logo Mundial 2026' },
      { code:'FWC5',  name:'Pelota oficial' },
      { code:'FWC6',  name:'Copa del Mundo Canadá' },
      { code:'FWC7',  name:'Copa del Mundo México' },
      { code:'FWC8',  name:'Copa del Mundo USA' },
    ]
  },

  // ── ESPECIALES (FWC tiles) ────────────────────────────────
  especiales: {
    label: 'FIFA Museum — Campeones del Mundo',
    items: [
      { code:'FWC9',  name:'Italia 1934' },
      { code:'FWC10', name:'Uruguay 1950' },
      { code:'FWC11', name:'Alemania 1954' },
      { code:'FWC12', name:'Brasil 1962' },
      { code:'FWC13', name:'Alemania 1974' },
      { code:'FWC14', name:'Argentina 1986' },
      { code:'FWC15', name:'Brasil 1994' },
      { code:'FWC16', name:'Brasil 2002' },
      { code:'FWC17', name:'Italia 2006' },
      { code:'FWC18', name:'Alemania 2014' },
      { code:'FWC19', name:'Argentina 2022' },
    ]
  },

  // ── CRACKS ───────────────────────────────────────────────
  cracks: {
    items: [
      { code: 'ARG17', name: 'Lionel Messi ⭐', realCode: 'ARG17' },
      { code: 'ARG18', name: 'Lautaro Martínez ⭐', realCode: 'ARG18' },
      { code: 'ARG19', name: 'Julián Álvarez ⭐', realCode: 'ARG19' },
      { code: 'POR20', name: 'Cristiano Ronaldo ⭐', realCode: 'POR20' },
      { code: 'FRA20', name: 'Kylian Mbappé ⭐', realCode: 'FRA20' },
      { code: 'BRA14', name: 'Vinicius Júnior ⭐', realCode: 'BRA14' },
      { code: 'BRA20', name: 'Estévão ⭐', realCode: 'BRA20' },
      { code: 'BRA19', name: 'Raphinha ⭐', realCode: 'BRA19' },
      { code: 'ENG11', name: 'Jude Bellingham ⭐', realCode: 'ENG11' },
      { code: 'ENG18', name: 'Harry Kane ⭐', realCode: 'ENG18' },
      { code: 'ESP11', name: 'Pedri ⭐', realCode: 'ESP11' },
      { code: 'ESP15', name: 'Lamine Yamal ⭐', realCode: 'ESP15' },
      { code: 'ESP17', name: 'Nico Williams ⭐', realCode: 'ESP17' },
      { code: 'GER11', name: 'Florian Wirtz ⭐', realCode: 'GER11' },
      { code: 'GER15', name: 'Jamal Musiala ⭐', realCode: 'GER15' },
      { code: 'NOR10', name: 'Martin Ødegaard ⭐', realCode: 'NOR10' },
      { code: 'EGY17', name: 'Mohamed Salah ⭐', realCode: 'EGY17' },
      { code: 'KOR18', name: 'Heung-min Son ⭐', realCode: 'KOR18' },
      { code: 'IRQ19', name: 'Aymen Hussein ⭐', realCode: 'IRQ19' },
      { code: 'URU10', name: 'Federico Valverde ⭐', realCode: 'URU10' },
      { code: 'COL20', name: 'Luis Díaz ⭐', realCode: 'COL20' },
      { code: 'NOR15', name: 'Erling Haaland ⭐', realCode: 'NOR15' },
      { code: 'BEL15', name: 'Kevin De Bruyne ⭐', realCode: 'BEL15' },
      { code: 'ESP10', name: 'Rodri ⭐', realCode: 'ESP10' }
    ]
  },

  // ── PROMO COCA-COLA ──────────────────────────────────────
  cocacola: {
    items: [
      { code: 'CC1',  name: 'Lamine Yamal' },
      { code: 'CC2',  name: 'Joshua Kimmich' },
      { code: 'CC3',  name: 'Harry Kane' },
      { code: 'CC4',  name: 'Santiago Giménez' },
      { code: 'CC5',  name: 'Joško Gvardiol' },
      { code: 'CC6',  name: 'Federico Valverde' },
      { code: 'CC7',  name: 'Jefferson Lerma' },
      { code: 'CC8',  name: 'Enner Valencia' },
      { code: 'CC9',  name: 'Gabriel Magalhães' },
      { code: 'CC10', name: 'Virgil van Dijk' },
      { code: 'CC11', name: 'Alphonso Davies' },
      { code: 'CC12', name: 'Emiliano Martínez' },
      { code: 'CC13', name: 'Raúl Jiménez' },
      { code: 'CC14', name: 'Lautaro Martínez' },
    ]
  },

  // ── EQUIPOS ─────────────────────────────────────────────
  // Estructura: escudo (num:0) + 18 jugadores (num:1-18) + foto grupal (num:19) = 20 por equipo
  teams: [
    { group:'J', name:'Argentina', flag:'ARG', players:[
      {num:1,  name:'Escudo Argentina'},
      {num:2, name:'Emiliano Martínez'},
      {num:3, name:'Nahuel Molina'},
      {num:4, name:'Cristian Romero'},
      {num:5, name:'Nicolás Otamendi'},
      {num:6, name:'Nicolás Tagliafico'},
      {num:7, name:'Leonardo Balerdi'},
      {num:8, name:'Enzo Fernández'},
      {num:9, name:'Alexis Mac Allister'},
      {num:10, name:'Rodrigo De Paul'},
      {num:11, name:'Exequiel Palacios'},
      {num:12, name:'Leandro Paredes'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Nico Paz'},
      {num:15, name:'Franco Mastantuono'},
      {num:16, name:'Nico González'},
      {num:17, name:'Lionel Messi'},
      {num:18, name:'Lautaro Martínez'},
      {num:19, name:'Julián Álvarez'},
      {num:20, name:'Giuliano Simeone'},
    ]},
    { group:'C', name:'Brasil', flag:'BRA', players:[
      {num:1,  name:'Escudo Brasil'},
      {num:2, name:'Alisson'},
      {num:3, name:'Bento'},
      {num:4, name:'Marquinhos'},
      {num:5, name:'Éder Militão'},
      {num:6, name:'Gabriel Magalhães'},
      {num:7, name:'Danilo'},
      {num:8, name:'Wesley'},
      {num:9, name:'Lucas Paquetá'},
      {num:10, name:'Casemiro'},
      {num:11, name:'Bruno Guimarães'},
      {num:12, name:'Luiz Henrique'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Vinicius Júnior'},
      {num:15, name:'Rodrygo'},
      {num:16, name:'João Pedro'},
      {num:17, name:'Matheus Cunha'},
      {num:18, name:'Gabriel Martinelli'},
      {num:19, name:'Raphinha'},
      {num:20, name:'Estévão'},
    ]},
    { group:'H', name:'Uruguay', flag:'URU', players:[
      {num:1,  name:'Escudo Uruguay'},
      {num:2, name:'Sergio Rochet'},
      {num:3, name:'Santiago Mele'},
      {num:4, name:'Ronald Araújo'},
      {num:5, name:'José María Giménez'},
      {num:6, name:'Sebastián Cáceres'},
      {num:7, name:'Mathias Olivera'},
      {num:8, name:'Guillermo Varela'},
      {num:9, name:'Nahitan Nández'},
      {num:10, name:'Federico Valverde'},
      {num:11, name:'Giorgian De Arrascaeta'},
      {num:12, name:'Rodrigo Bentancur'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Manuel Ugarte'},
      {num:15, name:'Nicolás de la Cruz'},
      {num:16, name:'Maxi Araújo'},
      {num:17, name:'Darwin Núñez'},
      {num:18, name:'Federico Viñas'},
      {num:19, name:'Rodrigo Aguirre'},
      {num:20, name:'Facundo Pellistri'},
    ]},
    { group:'K', name:'Colombia', flag:'COL', players:[
      {num:1,  name:'Escudo Colombia'},
      {num:2, name:'Camilo Vargas'},
      {num:3, name:'David Ospina'},
      {num:4, name:'Dávinson Sánchez'},
      {num:5, name:'Yerry Mina'},
      {num:6, name:'Daniel Muñoz'},
      {num:7, name:'Johan Mojica'},
      {num:8, name:'Jhon Lucumí'},
      {num:9, name:'Santiago Arias'},
      {num:10, name:'Jefferson Lerma'},
      {num:11, name:'Kevin Castaño'},
      {num:12, name:'Richard Ríos'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'James Rodríguez'},
      {num:15, name:'Juan Fernando Quintero'},
      {num:16, name:'Jorge Carrascal'},
      {num:17, name:'Jhon Arias'},
      {num:18, name:'Jhon Córdoba'},
      {num:19, name:'Luis Suárez'},
      {num:20, name:'Luis Díaz'},
    ]},
    { group:'E', name:'Ecuador', flag:'ECU', players:[
      {num:1,  name:'Escudo Ecuador'},
      {num:2, name:'Hernán Galíndez'},
      {num:3, name:'Gonzalo Valle'},
      {num:4, name:'Piero Hincapié'},
      {num:5, name:'Pervis Estupiñán'},
      {num:6, name:'Willian Pacho'},
      {num:7, name:'Ángelo Preciado'},
      {num:8, name:'Joel Ordóñez'},
      {num:9, name:'Moisés Caicedo'},
      {num:10, name:'Alan Franco'},
      {num:11, name:'Kendry Páez'},
      {num:12, name:'Pedro Vite'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'John Yeboah'},
      {num:15, name:'Leonardo Campana'},
      {num:16, name:'Gonzalo Plata'},
      {num:17, name:'Nilson Angulo'},
      {num:18, name:'Alan Minda'},
      {num:19, name:'Kevin Rodríguez'},
      {num:20, name:'Enner Valencia'},
    ]},
    { group:'D', name:'Paraguay', flag:'PAR', players:[
      {num:1,  name:'Escudo Paraguay'},
      {num:2, name:'Roberto Fernández'},
      {num:3, name:'Orlando Gill'},
      {num:4, name:'Gustavo Gómez'},
      {num:5, name:'Fabián Balbuena'},
      {num:6, name:'Juan José Cáceres'},
      {num:7, name:'Omar Alderete'},
      {num:8, name:'Junior Alonso'},
      {num:9, name:'Mathías Villasanti'},
      {num:10, name:'Diego Gómez'},
      {num:11, name:'Damián Bobadilla'},
      {num:12, name:'Andrés Cubas'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Matías Galarza'},
      {num:15, name:'Julio Enciso'},
      {num:16, name:'Alejandro Romero Gamarra'},
      {num:17, name:'Miguel Almirón'},
      {num:18, name:'Ramón Sosa'},
      {num:19, name:'Ángel Romero'},
      {num:20, name:'Antonio Sanabria'},
    ]},
    { group:'H', name:'España', flag:'ESP', players:[
      {num:1,  name:'Escudo España'},
      {num:2, name:'Unai Simón'},
      {num:3, name:'Robin Le Normand'},
      {num:4, name:'Aymeric Laporte'},
      {num:5, name:'Dean Huijsen'},
      {num:6, name:'Pedro Porro'},
      {num:7, name:'Dani Carvajal'},
      {num:8, name:'Marc Cucurella'},
      {num:9, name:'Martín Zubimendi'},
      {num:10, name:'Rodri'},
      {num:11, name:'Pedri'},
      {num:12, name:'Fabián Ruiz'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Mikel Merino'},
      {num:15, name:'Lamine Yamal'},
      {num:16, name:'Dani Olmo'},
      {num:17, name:'Nico Williams'},
      {num:18, name:'Ferran Torres'},
      {num:19, name:'Álvaro Morata'},
      {num:20, name:'Mikel Oyarzabal'},
    ]},
    { group:'I', name:'Francia', flag:'FRA', players:[
      {num:1,  name:'Escudo Francia'},
      {num:2, name:'Mike Maignan'},
      {num:3, name:'Theo Hernandez'},
      {num:4, name:'William Saliba'},
      {num:5, name:'Jules Koundé'},
      {num:6, name:'Ibrahima Konaté'},
      {num:7, name:'Dayot Upamecano'},
      {num:8, name:'Lucas Digne'},
      {num:9, name:'Aurélien Tchouaméni'},
      {num:10, name:'Eduardo Camavinga'},
      {num:11, name:'Manu Koné'},
      {num:12, name:'Adrien Rabiot'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Michael Olise'},
      {num:15, name:'Ousmane Dembélé'},
      {num:16, name:'Bradley Barcola'},
      {num:17, name:'Désiré Doué'},
      {num:18, name:'Kingsley Coman'},
      {num:19, name:'Hugo Ekitiké'},
      {num:20, name:'Kylian Mbappé'},
    ]},
    { group:'E', name:'Alemania', flag:'GER', players:[
      {num:1,  name:'Escudo Alemania'},
      {num:2, name:'Marc-André ter Stegen'},
      {num:3, name:'Jonathan Tah'},
      {num:4, name:'David Raum'},
      {num:5, name:'Nico Schlotterbeck'},
      {num:6, name:'Antonio Rüdiger'},
      {num:7, name:'Waldemar Anton'},
      {num:8, name:'Ridle Baku'},
      {num:9, name:'Maximilian Mittelstadt'},
      {num:10, name:'Joshua Kimmich'},
      {num:11, name:'Florian Wirtz'},
      {num:12, name:'Felix Nmecha'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Leon Goretzka'},
      {num:15, name:'Jamal Musiala'},
      {num:16, name:'Serge Gnabry'},
      {num:17, name:'Kai Havertz'},
      {num:18, name:'Leroy Sané'},
      {num:19, name:'Karim Adeyemi'},
      {num:20, name:'Nick Woltemade'},
    ]},
    { group:'L', name:'Inglaterra', flag:'ENG', players:[
      {num:1,  name:'Escudo Inglaterra'},
      {num:2, name:'Jordan Pickford'},
      {num:3, name:'John Stones'},
      {num:4, name:'Marc Guéhi'},
      {num:5, name:'Ezri Konsa'},
      {num:6, name:'Trent Alexander-Arnold'},
      {num:7, name:'Reece James'},
      {num:8, name:'Dan Burn'},
      {num:9, name:'Jordan Henderson'},
      {num:10, name:'Declan Rice'},
      {num:11, name:'Jude Bellingham'},
      {num:12, name:'Cole Palmer'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Morgan Rogers'},
      {num:15, name:'Anthony Gordon'},
      {num:16, name:'Phil Foden'},
      {num:17, name:'Bukayo Saka'},
      {num:18, name:'Harry Kane'},
      {num:19, name:'Marcus Rashford'},
      {num:20, name:'Ollie Watkins'},
    ]},
    { group:'K', name:'Portugal', flag:'POR', players:[
      {num:1,  name:'Escudo Portugal'},
      {num:2,  name:'Diogo Costa'},
      {num:3,  name:'José Sá'},
      {num:4,  name:'Rúben Dias'},
      {num:5,  name:'João Cancelo'},
      {num:6,  name:'Diogo Dalot'},
      {num:7,  name:'Nuno Mendes'},
      {num:8,  name:'Gonçalo Inácio'},
      {num:9,  name:'Bernardo Silva'},
      {num:10, name:'Bruno Fernandes'},
      {num:11, name:'Rúben Neves'},
      {num:12, name:'Vitinha'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'João Neves'},
      {num:15, name:'Cristiano Ronaldo'},
      {num:16, name:'Francisco Trincão'},
      {num:17, name:'João Félix'},
      {num:18, name:'Gonçalo Ramos'},
      {num:19, name:'Pedro Neto'},
      {num:20, name:'Rafael Leão'},
    ]},
    { group:'F', name:'Países Bajos', flag:'NED', players:[
      {num:1,  name:'Escudo Países Bajos'},
      {num:2, name:'Bart Verbruggen'},
      {num:3, name:'Virgil van Dijk'},
      {num:4, name:'Micky van de Ven'},
      {num:5, name:'Jurrien Timber'},
      {num:6, name:'Denzel Dumfries'},
      {num:7, name:'Nathan Aké'},
      {num:8, name:'Jeremie Frimpong'},
      {num:9, name:'Jan Paul van Hecke'},
      {num:10, name:'Tijjani Reijnders'},
      {num:11, name:'Ryan Gravenberch'},
      {num:12, name:'Teun Koopmeiners'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Frenkie de Jong'},
      {num:15, name:'Xavi Simons'},
      {num:16, name:'Justin Kluivert'},
      {num:17, name:'Memphis Depay'},
      {num:18, name:'Donyell Malen'},
      {num:19, name:'Wout Weghorst'},
      {num:20, name:'Cody Gakpo'},
    ]},
    { group:'G', name:'Bélgica', flag:'BEL', players:[
      {num:1,  name:'Escudo Bélgica'},
      {num:2, name:'Thibaut Courtois'},
      {num:3, name:'Arthur Theate'},
      {num:4, name:'Timothy Castagne'},
      {num:5, name:'Zeno Debast'},
      {num:6, name:'Brandon Mechele'},
      {num:7, name:'Maxim De Cuyper'},
      {num:8, name:'Thomas Meunier'},
      {num:9, name:'Youri Tielemans'},
      {num:10, name:'Amadou Onana'},
      {num:11, name:'Nicolas Raskin'},
      {num:12, name:'Alexis Saelemaekers'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Hans Vanaken'},
      {num:15, name:'Kevin De Bruyne'},
      {num:16, name:'Jérémy Doku'},
      {num:17, name:'Charles De Ketelaere'},
      {num:18, name:'Leandro Trossard'},
      {num:19, name:'Loïs Openda'},
      {num:20, name:'Romelu Lukaku'},
    ]},
    { group:'B', name:'Suiza', flag:'SUI', players:[
      {num:1,  name:'Escudo Suiza'},
      {num:2, name:'Gregor Kobel'},
      {num:3, name:'Yvon Mvogo'},
      {num:4, name:'Manuel Akanji'},
      {num:5, name:'Ricardo Rodríguez'},
      {num:6, name:'Nico Elvedi'},
      {num:7, name:'Aurèle Amenda'},
      {num:8, name:'Silvan Widmer'},
      {num:9, name:'Granit Xhaka'},
      {num:10, name:'Denis Zakaria'},
      {num:11, name:'Remo Freuler'},
      {num:12, name:'Fabian Rieder'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Ardon Jashari'},
      {num:15, name:'Johan Manzambi'},
      {num:16, name:'Michel Aebischer'},
      {num:17, name:'Breel Embolo'},
      {num:18, name:'Ruben Vargas'},
      {num:19, name:'Dan Ndoye'},
      {num:20, name:'Zeki Amdouni'},
    ]},
    { group:'L', name:'Croacia', flag:'CRO', players:[
      {num:1,  name:'Escudo Croacia'},
      {num:2,  name:'Dominik Livaković'},
      {num:3,  name:'Duje Ćaleta-Car'},
      {num:4,  name:'Joško Gvardiol'},
      {num:5,  name:'Josip Stanišić'},
      {num:6,  name:'Martin Erlić'},
      {num:7,  name:'Josip Šutalo'},
      {num:8,  name:'Kristijan Jakić'},
      {num:9,  name:'Luka Modrić'},
      {num:10, name:'Mateo Kovačić'},
      {num:11, name:'Martin Baturina'},
      {num:12, name:'Lovro Majer'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Mario Pašalić'},
      {num:15, name:'Petar Sucić'},
      {num:16, name:'Ivan Perišić'},
      {num:17, name:'Marco Pašalić'},
      {num:18, name:'Ante Budimir'},
      {num:19, name:'Andrej Kramarić'},
      {num:20, name:'Franjo Ivanović'},
    ]},
    { group:'C', name:'Escocia', flag:'SCO', players:[
      {num:1,  name:'Escudo Escocia'},
      {num:2, name:'Angus Gunn'},
      {num:3, name:'Jack Hendry'},
      {num:4, name:'Kieran Tierney'},
      {num:5, name:'Aaron Hickey'},
      {num:6, name:'Andrew Robertson'},
      {num:7, name:'Scott McKenna'},
      {num:8, name:'John Souttar'},
      {num:9, name:'Anthony Ralston'},
      {num:10, name:'Grant Hanley'},
      {num:11, name:'Scott McTominay'},
      {num:12, name:'Billy Gilmour'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Lewis Ferguson'},
      {num:15, name:'Ryan Christie'},
      {num:16, name:'Kenny McLean'},
      {num:17, name:'John McGinn'},
      {num:18, name:'Lyndon Dykes'},
      {num:19, name:'Che Adams'},
      {num:20, name:'Ben Doak'},
    ]},
    { group:'J', name:'Austria', flag:'AUT', players:[
      {num:1,  name:'Escudo Austria'},
      {num:2, name:'Alexander Schlager'},
      {num:3, name:'Patrick Pentz'},
      {num:4, name:'David Alaba'},
      {num:5, name:'Kevin Danso'},
      {num:6, name:'Philipp Lienhart'},
      {num:7, name:'Stefan Posch'},
      {num:8, name:'Philipp Mwene'},
      {num:9, name:'Alexander Prass'},
      {num:10, name:'Xaver Schlager'},
      {num:11, name:'Marcel Sabitzer'},
      {num:12, name:'Konrad Laimer'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Florian Grillitsch'},
      {num:15, name:'Nicolas Seiwald'},
      {num:16, name:'Romano Schmid'},
      {num:17, name:'Patrick Wimmer'},
      {num:18, name:'Christoph Baumgartner'},
      {num:19, name:'Michael Gregoritsch'},
      {num:20, name:'Marko Arnautović'},
    ]},
    { group:'D', name:'Turquía', flag:'TUR', players:[
      {num:1,  name:'Escudo Turquía'},
      {num:2, name:'Uğurcan Çakır'},
      {num:3, name:'Mert Müldür'},
      {num:4, name:'Zeki Çelik'},
      {num:5, name:'Abdülkerim Bardakcı'},
      {num:6, name:'Çağlar Söyüncü'},
      {num:7, name:'Merih Demiral'},
      {num:8, name:'Ferdi Kadıoğlu'},
      {num:9, name:'Kaan Ayhan'},
      {num:10, name:'İsmail Yüksek'},
      {num:11, name:'Hakan Çalhanoğlu'},
      {num:12, name:'Orkun Kökçü'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Arda Güler'},
      {num:15, name:'İrfan Can Kahveci'},
      {num:16, name:'Yunus Akgün'},
      {num:17, name:'Can Uzun'},
      {num:18, name:'Barış Alper Yılmaz'},
      {num:19, name:'Kerem Aktürkoğlu'},
      {num:20, name:'Kenan Yıldız'},
    ]},
    { group:'I', name:'Noruega', flag:'NOR', players:[
      {num:1,  name:'Escudo Noruega'},
      {num:2, name:'Ørjan Nyland'},
      {num:3, name:'Julian Ryerson'},
      {num:4, name:'Leo Østigård'},
      {num:5, name:'Kristoffer Ajer'},
      {num:6, name:'Marcus Holmgren Pedersen'},
      {num:7, name:'David Møller Wolfe'},
      {num:8, name:'Torbjørn Heggem'},
      {num:9, name:'Morten Thorsby'},
      {num:10, name:'Martin Ødegaard'},
      {num:11, name:'Sander Berge'},
      {num:12, name:'Andreas Schjelderup'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Patrick Berg'},
      {num:15, name:'Erling Haaland'},
      {num:16, name:'Alexander Sørloth'},
      {num:17, name:'Aron Dønnum'},
      {num:18, name:'Jørgen Strand Larsen'},
      {num:19, name:'Antonio Nusa'},
      {num:20, name:'Oscar Bobb'},
    ]},
    { group:'F', name:'Suecia', flag:'SWE', players:[
      {num:1,  name:'Escudo Suecia'},
      {num:2, name:'Victor Johansson'},
      {num:3, name:'Isak Hien'},
      {num:4, name:'Gabriel Gudmundsson'},
      {num:5, name:'Emil Holm'},
      {num:6, name:'Victor Nilsson Lindelöf'},
      {num:7, name:'Gustaf Lagerbielke'},
      {num:8, name:'Lucas Bergvall'},
      {num:9, name:'Hugo Larsson'},
      {num:10, name:'Jesper Karlström'},
      {num:11, name:'Yasin Ayari'},
      {num:12, name:'Mattias Svanberg'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Daniel Svensson'},
      {num:15, name:'Ken Sema'},
      {num:16, name:'Roony Bardghji'},
      {num:17, name:'Dejan Kulusevski'},
      {num:18, name:'Anthony Elanga'},
      {num:19, name:'Alexander Isak'},
      {num:20, name:'Viktor Gyökeres'},
    ]},
    { group:'B', name:'Bosnia y Herz.', flag:'BIH', players:[
      {num:1,  name:'Escudo Bosnia y Herz.'},
      {num:2, name:'Nikola Vasilj'},
      {num:3, name:'Amer Dedić'},
      {num:4, name:'Sead Kolašinac'},
      {num:5, name:'Tarik Muharemović'},
      {num:6, name:'Nihad Mujakić'},
      {num:7, name:'Nikola Katić'},
      {num:8, name:'Amir Hadžiahmetović'},
      {num:9, name:'Benjamin Tahirović'},
      {num:10, name:'Armin Gigović'},
      {num:11, name:'Ivan Sunjić'},
      {num:12, name:'Ivan Bašić'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Dženis Burnić'},
      {num:15, name:'Esmir Bajraktarević'},
      {num:16, name:'Amar Memić'},
      {num:17, name:'Ermedin Demirović'},
      {num:18, name:'Edin Džeko'},
      {num:19, name:'Samed Baždar'},
      {num:20, name:'Haris Tabakovic'},
    ]},
    { group:'A', name:'República Checa', flag:'CZE', players:[
      {num:1,  name:'Escudo República Checa'},
      {num:2, name:'Matěj Kovář'},
      {num:3, name:'Jindřich Staněk'},
      {num:4, name:'Ladislav Krejčí'},
      {num:5, name:'Vladimír Coufal'},
      {num:6, name:'Jaroslav Zelený'},
      {num:7, name:'Tomáš Holeš'},
      {num:8, name:'David Zima'},
      {num:9, name:'Michal Sadílek'},
      {num:10, name:'Lukáš Provod'},
      {num:11, name:'Lukáš Červ'},
      {num:12, name:'Tomáš Souček'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Pavel Šulc'},
      {num:15, name:'Matěj Vydra'},
      {num:16, name:'Vasil Kušej'},
      {num:17, name:'Tomáš Chorý'},
      {num:18, name:'Václav Černý'},
      {num:19, name:'Adam Hložek'},
      {num:20, name:'Patrik Schick'},
    ]},
    { group:'A', name:'México', flag:'MEX', players:[
      {num:1,  name:'Escudo México'},
      {num:2, name:'Luis Malagón'},
      {num:3, name:'Johan Vásquez'},
      {num:4, name:'Jorge Sánchez'},
      {num:5, name:'César Montes'},
      {num:6, name:'Jesús Gallardo'},
      {num:7, name:'Israel Reyes'},
      {num:8, name:'Diego Lainez'},
      {num:9, name:'Carlos Rodríguez'},
      {num:10, name:'Edson Álvarez'},
      {num:11, name:'Orbelín Pineda'},
      {num:12, name:'Marcel Ruiz'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Érick Sánchez'},
      {num:15, name:'Hirving Lozano'},
      {num:16, name:'Santiago Giménez'},
      {num:17, name:'Raúl Jiménez'},
      {num:18, name:'Alexis Vega'},
      {num:19, name:'Roberto Alvarado'},
      {num:20, name:'César Huerta'},
    ]},
    { group:'D', name:'EE.UU.', flag:'USA', players:[
      {num:1,  name:'Escudo EE.UU.'},
      {num:2, name:'Matt Freese'},
      {num:3, name:'Chris Richards'},
      {num:4, name:'Tim Ream'},
      {num:5, name:'Mark McKenzie'},
      {num:6, name:'Alex Freeman'},
      {num:7, name:'Antonee Robinson'},
      {num:8, name:'Tyler Adams'},
      {num:9, name:'Tanner Tessmann'},
      {num:10, name:'Weston McKennie'},
      {num:11, name:'Christian Roldán'},
      {num:12, name:'Timothy Weah'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Diego Luna'},
      {num:15, name:'Malik Tillman'},
      {num:16, name:'Christian Pulisic'},
      {num:17, name:'Brenden Aaronson'},
      {num:18, name:'Ricardo Pepi'},
      {num:19, name:'Haji Wright'},
      {num:20, name:'Folarin Balogun'},
    ]},
    { group:'B', name:'Canadá', flag:'CAN', players:[
      {num:1,  name:'Escudo Canadá'},
      {num:2, name:'Dayne St. Clair'},
      {num:3, name:'Alphonso Davies'},
      {num:4, name:'Alistair Johnston'},
      {num:5, name:'Samuel Adekugbe'},
      {num:6, name:'Richer Laryea'},
      {num:7, name:'Derek Cornelius'},
      {num:8, name:'Moïse Bombito'},
      {num:9, name:'Kamal Miller'},
      {num:10, name:'Stephen Eustáquio'},
      {num:11, name:'Ismaël Koné'},
      {num:12, name:'Jonathan Osorio'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Jacob Shaffelburg'},
      {num:15, name:'Mathieu Choinière'},
      {num:16, name:'Niko Sigur'},
      {num:17, name:'Tajon Buchanan'},
      {num:18, name:'Liam Millar'},
      {num:19, name:'Cyle Larin'},
      {num:20, name:'Jonathan David'},
    ]},
    { group:'L', name:'Panamá', flag:'PAN', players:[
      {num:1,  name:'Escudo Panamá'},
      {num:2, name:'Orlando Mosquera'},
      {num:3, name:'Fidel Escobar'},
      {num:4, name:'César Yanis'},
      {num:5, name:'Harold Cummings'},
      {num:6, name:'Éric Davis'},
      {num:7, name:'Andrés Andrade'},
      {num:8, name:'José Córdoba'},
      {num:9, name:'Adalberto Carrasquilla'},
      {num:10, name:'Iván Anderson'},
      {num:11, name:'Aníbal Godoy'},
      {num:12, name:'Armando Cooper'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Freddy Góndola'},
      {num:15, name:'Roderick Miller'},
      {num:16, name:'Ismael Díaz'},
      {num:17, name:'Édgar Bárcenas'},
      {num:18, name:'Rolando Blackburn'},
      {num:19, name:'José Luis Rodríguez'},
      {num:20, name:'Alberto Quintero'},
    ]},
    { group:'C', name:'Haití', flag:'HAI', players:[
      {num:1,  name:'Escudo Haití'},
      {num:2, name:'Johny Placide'},
      {num:3, name:'Carlens Arcus'},
      {num:4, name:'Martin Expérience'},
      {num:5, name:'Jean-Kevin Duverne'},
      {num:6, name:'Ricardo Adé'},
      {num:7, name:'Duke Lacroix'},
      {num:8, name:'Garven Metusala'},
      {num:9, name:'Hannes Delcroix'},
      {num:10, name:'Leverton Pierre'},
      {num:11, name:'Danley Jean Jacques'},
      {num:12, name:'Jean-Ricner Bellegarde'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Christopher Attys'},
      {num:15, name:'Derrick Etienne Jr.'},
      {num:16, name:'Josué Casimir'},
      {num:17, name:'Ruben Providence'},
      {num:18, name:'Duckens Nazon'},
      {num:19, name:'Louicius Deedson'},
      {num:20, name:'Frantzdy Pierrot'},
    ]},
    { group:'E', name:'Curazao', flag:'CUW', players:[
      {num:1,  name:'Escudo Curazao'},
      {num:2, name:'Eloy Room'},
      {num:3, name:'Armando Obispo'},
      {num:4, name:'Sherel Floranus'},
      {num:5, name:'Jurien Gaari'},
      {num:6, name:'Joshua Brenet'},
      {num:7, name:'Roshon Van Eijma'},
      {num:8, name:'Shurandy Sambo'},
      {num:9, name:'Livano Comenencia'},
      {num:10, name:'Godfried Roemeratoe'},
      {num:11, name:'Juninho Bacuna'},
      {num:12, name:'Leandro Bacuna'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Tahith Chong'},
      {num:15, name:'Kenji Gorre'},
      {num:16, name:'Jearl Margaritha'},
      {num:17, name:'Jurgen Locadia'},
      {num:18, name:'Jeremy Antonisse'},
      {num:19, name:'Gervane Kastaneer'},
      {num:20, name:'Sontje Hansen'},
    ]},
    { group:'C', name:'Marruecos', flag:'MAR', players:[
      {num:1,  name:'Escudo Marruecos'},
      {num:2, name:'Yassine Bounou'},
      {num:3, name:'Munir El Kajoui'},
      {num:4, name:'Achraf Hakimi'},
      {num:5, name:'Noussair Mazraoui'},
      {num:6, name:'Nayef Aguerd'},
      {num:7, name:'Romain Saïss'},
      {num:8, name:'Jawad El Yamiq'},
      {num:9, name:'Adam Masina'},
      {num:10, name:'Sofyan Amrabat'},
      {num:11, name:'Azzedine Ounahi'},
      {num:12, name:'Eliesse Ben Seghir'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Bilal El Khannous'},
      {num:15, name:'Ismael Saibari'},
      {num:16, name:'Youssef En-Nesyri'},
      {num:17, name:'Abde Ezzalzouli'},
      {num:18, name:'Soufiane Rahimi'},
      {num:19, name:'Brahim Díaz'},
      {num:20, name:'Ayoub El Kaabi'},
    ]},
    { group:'I', name:'Senegal', flag:'SEN', players:[
      {num:1,  name:'Escudo Senegal'},
      {num:2, name:'Édouard Mendy'},
      {num:3, name:'Yehvann Diouf'},
      {num:4, name:'Moussa Niakhaté'},
      {num:5, name:'Abdoulaye Seck'},
      {num:6, name:'Ismail Jakobs'},
      {num:7, name:'El Hadji Malick Diouf'},
      {num:8, name:'Kalidou Koulibaly'},
      {num:9, name:'Idrissa Gana Gueye'},
      {num:10, name:'Pape Matar Sarr'},
      {num:11, name:'Pape Gueye'},
      {num:12, name:'Habib Diarra'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Lamine Camara'},
      {num:15, name:'Sadio Mané'},
      {num:16, name:'Ismaïla Sarr'},
      {num:17, name:'Boulaye Dia'},
      {num:18, name:'Iliman Ndiaye'},
      {num:19, name:'Nicolas Jackson'},
      {num:20, name:'Krepin Diatta'},
    ]},
    { group:'E', name:'Costa de Marfil', flag:'CIV', players:[
      {num:1,  name:'Escudo Costa de Marfil'},
      {num:2, name:'Yahia Fofana'},
      {num:3, name:'Ghislain Konan'},
      {num:4, name:'Wilfried Singo'},
      {num:5, name:'Odilon Kossounou'},
      {num:6, name:'Evan N\'Dicka'},
      {num:7, name:'Willy Boly'},
      {num:8, name:'Emmanuel Agbadou'},
      {num:9, name:'Ousmane Diomandé'},
      {num:10, name:'Franck Kessié'},
      {num:11, name:'Seko Fofana'},
      {num:12, name:'Ibrahim Sangaré'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Jean-Philippe Gbamin'},
      {num:15, name:'Amad Diallo'},
      {num:16, name:'Sébastien Haller'},
      {num:17, name:'Simon Adingra'},
      {num:18, name:'Yan Diomandé'},
      {num:19, name:'Evann Guessand'},
      {num:20, name:'Oumar Diakité'},
    ]},
    { group:'G', name:'Egipto', flag:'EGY', players:[
      {num:1,  name:'Escudo Egipto'},
      {num:2, name:'Mohamed El Shenawy'},
      {num:3, name:'Mohamed Hany'},
      {num:4, name:'Mohamed Hamdy'},
      {num:5, name:'Yasser Ibrahim'},
      {num:6, name:'Khaled Sobhi'},
      {num:7, name:'Ramy Rabia'},
      {num:8, name:'Hossam Abdelmaguid'},
      {num:9, name:'Ahmed Fatouh'},
      {num:10, name:'Marwan Attia'},
      {num:11, name:'Zizo'},
      {num:12, name:'Hamdy Fathy'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Mohamed Lasheen'},
      {num:15, name:'Emam Ashour'},
      {num:16, name:'Osama Faisal'},
      {num:17, name:'Mohamed Salah'},
      {num:18, name:'Mostafa Mohamed'},
      {num:19, name:'Trezeguet'},
      {num:20, name:'Omar Marmoush'},
    ]},
    { group:'J', name:'Argelia', flag:'ALG', players:[
      {num:1,  name:'Escudo Argelia'},
      {num:2, name:'Alexis Guendouz'},
      {num:3, name:'Ramy Bensebaïni'},
      {num:4, name:'Youcef Atal'},
      {num:5, name:'Rayan Aït-Nouri'},
      {num:6, name:'Mohamed Amine Tougai'},
      {num:7, name:'Aïssa Mandi'},
      {num:8, name:'Ismaël Bennacer'},
      {num:9, name:'Houssem Aouar'},
      {num:10, name:'Hicham Boudaoui'},
      {num:11, name:'Ramiz Zerrouki'},
      {num:12, name:'Nabil Bentalab'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Farès Chaibi'},
      {num:15, name:'Riyad Mahrez'},
      {num:16, name:'Saïd Benrahma'},
      {num:17, name:'Anis Hadj Moussa'},
      {num:18, name:'Amine Gouiri'},
      {num:19, name:'Baghdad Bounedjah'},
      {num:20, name:'Mohammed Amoura'},
    ]},
    { group:'A', name:'Sudáfrica', flag:'RSA', players:[
      {num:1,  name:'Escudo Sudáfrica'},
      {num:2, name:'Ronwen Williams'},
      {num:3, name:'Sipho Chaine'},
      {num:4, name:'Aubrey Modiba'},
      {num:5, name:'Samukele Kabini'},
      {num:6, name:'Mbekezeli Mbokazi'},
      {num:7, name:'Khulumani Ndamane'},
      {num:8, name:'Siyabonga Ngezana'},
      {num:9, name:'Khuliso Mudau'},
      {num:10, name:'Nkosinathi Sibisi'},
      {num:11, name:'Teboho Mokoena'},
      {num:12, name:'Thalente Mbatha'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Bathasi Aubaas'},
      {num:15, name:'Yaya Sithole'},
      {num:16, name:'Sipho Mbule'},
      {num:17, name:'Lyle Foster'},
      {num:18, name:'Iqraam Rayners'},
      {num:19, name:'Mohau Nkota'},
      {num:20, name:'Oswin Appollis'},
    ]},
    { group:'F', name:'Túnez', flag:'TUN', players:[
      {num:1,  name:'Escudo Túnez'},
      {num:2, name:'Bechir Ben Said'},
      {num:3, name:'Aymen Dahmen'},
      {num:4, name:'Yan Valery'},
      {num:5, name:'Montassar Talbi'},
      {num:6, name:'Yassine Mériah'},
      {num:7, name:'Ali Abdi'},
      {num:8, name:'Dylan Bronn'},
      {num:9, name:'Ellyes Skhiri'},
      {num:10, name:'Aissa Laidouni'},
      {num:11, name:'Ferjani Sassi'},
      {num:12, name:'Mohamed Ali Ben Romdhane'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Hannibal Mejbri'},
      {num:15, name:'Elias Achouri'},
      {num:16, name:'Elias Saad'},
      {num:17, name:'Hazem Mastouri'},
      {num:18, name:'Ismael Gharbi'},
      {num:19, name:'Sayfallah Ltaief'},
      {num:20, name:'Naim Sliti'},
    ]},
    { group:'L', name:'Ghana', flag:'GHA', players:[
      {num:1,  name:'Escudo Ghana'},
      {num:2, name:'Lawrence Ati-Zigi'},
      {num:3, name:'Alexander Djiku'},
      {num:4, name:'Daniel Amartey'},
      {num:5, name:'Denis Odoi'},
      {num:6, name:'Gideon Mensah'},
      {num:7, name:'Tariq Lamptey'},
      {num:8, name:'Elisha Owusu'},
      {num:9, name:'Thomas Partey'},
      {num:10, name:'Salis Abdul Samed'},
      {num:11, name:'Antoine Semenyo'},
      {num:12, name:'Braydon Manu'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Mohammed Kudus'},
      {num:15, name:'Jordan Ayew'},
      {num:16, name:'André Ayew'},
      {num:17, name:'Osman Bukari'},
      {num:18, name:'Iñaki Williams'},
      {num:19, name:'Felix Afena-Gyan'},
      {num:20, name:'Ernest Nuamah'},
    ]},
    { group:'H', name:'Cabo Verde', flag:'CPV', players:[
      {num:1,  name:'Escudo Cabo Verde'},
      {num:2, name:'Vozinha'},
      {num:3, name:'Logan Costa'},
      {num:4, name:'Pico'},
      {num:5, name:'Diney'},
      {num:6, name:'Steven Moreira'},
      {num:7, name:'Wagner Pina'},
      {num:8, name:'Joao Paulo'},
      {num:9, name:'Yannick Semedo'},
      {num:10, name:'Kevin Pina'},
      {num:11, name:'Patrick Andrade'},
      {num:12, name:'Jamiro Monteiro'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Deroy Duarte'},
      {num:15, name:'Garry Rodrigues'},
      {num:16, name:'Jovane Cabral'},
      {num:17, name:'Ryan Mendes'},
      {num:18, name:'Dailon Livramento'},
      {num:19, name:'Willy Semedo'},
      {num:20, name:'Bebé'},
    ]},
    { group:'K', name:'Congo DR', flag:'COD', players:[
      {num:1,  name:'Escudo Congo DR'},
      {num:2, name:'Lionel Mpasi'},
      {num:3, name:'Aaron Wan-Bissaka'},
      {num:4, name:'Axel Tuanzebe'},
      {num:5, name:'Arthur Masuaku'},
      {num:6, name:'Chancel Mbemba'},
      {num:7, name:'Joris Kayembe'},
      {num:8, name:'Charles Pickel'},
      {num:9, name:'Ngal\'ayel Mukau'},
      {num:10, name:'Edo Kayembe'},
      {num:11, name:'Samuel Moutoussamy'},
      {num:12, name:'Noah Sadiki'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Théo Bongonda'},
      {num:15, name:'Meschak Elia'},
      {num:16, name:'Yoane Wissa'},
      {num:17, name:'Brian Cipenga'},
      {num:18, name:'Fiston Mayele'},
      {num:19, name:'Cédric Bakambu'},
      {num:20, name:'Nathanaël Mbuku'},
    ]},
    { group:'F', name:'Japón', flag:'JPN', players:[
      {num:1,  name:'Escudo Japón'},
      {num:2, name:'Zion Suzuki'},
      {num:3, name:'Henry Heroki Mochizuki'},
      {num:4, name:'Ayumu Seko'},
      {num:5, name:'Junnosuke Suzuki'},
      {num:6, name:'Shogo Taniguchi'},
      {num:7, name:'Tsuyoshi Watanabe'},
      {num:8, name:'Kaishu Sano'},
      {num:9, name:'Yuki Soma'},
      {num:10, name:'Ao Tanaka'},
      {num:11, name:'Daichi Kamada'},
      {num:12, name:'Takefusa Kubo'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Ritsu Doan'},
      {num:15, name:'Keito Nakamura'},
      {num:16, name:'Takumi Minamino'},
      {num:17, name:'Shuto Machino'},
      {num:18, name:'Junya Ito'},
      {num:19, name:'Koki Ogawa'},
      {num:20, name:'Ayase Ueda'},
    ]},
    { group:'A', name:'Corea del Sur', flag:'KOR', players:[
      {num:1,  name:'Escudo Corea del Sur'},
      {num:2, name:'Hyeon-woo Jo'},
      {num:3, name:'Seung-Gyu Kim'},
      {num:4, name:'Min-jae Kim'},
      {num:5, name:'Yu-min Cho'},
      {num:6, name:'Young-woo Seol'},
      {num:7, name:'Han-beom Lee'},
      {num:8, name:'Tae-seok Lee'},
      {num:9, name:'Myung-jae Lee'},
      {num:10, name:'Jae-sung Lee'},
      {num:11, name:'In-beom Hwang'},
      {num:12, name:'Kang-in Lee'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Seung-ho Paik'},
      {num:15, name:'Jens Castrop'},
      {num:16, name:'Dong-yeong Lee'},
      {num:17, name:'Gue-sung Cho'},
      {num:18, name:'Heung-min Son'},
      {num:19, name:'Hee-chan Hwang'},
      {num:20, name:'Hyeon-Gyu Oh'},
    ]},
    { group:'H', name:'Arabia Saudita', flag:'KSA', players:[
      {num:1,  name:'Escudo Arabia Saudita'},
      {num:2, name:'Nawaf Alaqidi'},
      {num:3, name:'Abdulrahman Al-Sanbi'},
      {num:4, name:'Saud Abdulhamid'},
      {num:5, name:'Nawaf Bouwashl'},
      {num:6, name:'Jihad Thakri'},
      {num:7, name:'Moteb Al-Harbi'},
      {num:8, name:'Hassan Altambakti'},
      {num:9, name:'Musab Aljuwayr'},
      {num:10, name:'Ziyad Aljohani'},
      {num:11, name:'Abdullah Alkhaibari'},
      {num:12, name:'Nasser Aldawsari'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Saleh Abu Alshamat'},
      {num:15, name:'Marwan Alsahafi'},
      {num:16, name:'Salem Aldawsari'},
      {num:17, name:'Abdulrahman Al-Aboud'},
      {num:18, name:'Feras Akbrikan'},
      {num:19, name:'Saleh Alshehri'},
      {num:20, name:'Abdullah Al-Hamdan'},
    ]},
    { group:'G', name:'Irán', flag:'IRN', players:[
      {num:1,  name:'Escudo Irán'},
      {num:2, name:'Alireza Beiranvand'},
      {num:3, name:'Morteza Pouraliganji'},
      {num:4, name:'Ehsan Hajsafi'},
      {num:5, name:'Milad Mohammadi'},
      {num:6, name:'Shojae Khalilzadeh'},
      {num:7, name:'Ramin Rezaeian'},
      {num:8, name:'Hossein Kanaani'},
      {num:9, name:'Sadegh Moharrami'},
      {num:10, name:'Saleh Hardani'},
      {num:11, name:'Saeed Ezatolahi'},
      {num:12, name:'Saman Ghoddos'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Omid Noorafkan'},
      {num:15, name:'Roozbeh Cheshmi'},
      {num:16, name:'Mohammad Mohebi'},
      {num:17, name:'Sardar Azmoun'},
      {num:18, name:'Mehdi Taremi'},
      {num:19, name:'Alireza Jahanbakhsh'},
      {num:20, name:'Ali Gholizadeh'},
    ]},
    { group:'B', name:'Qatar', flag:'QAT', players:[
      {num:1,  name:'Escudo Qatar'},
      {num:2, name:'Meshaal Barsham'},
      {num:3, name:'Sultan Albrake'},
      {num:4, name:'Lucas Mendes'},
      {num:5, name:'Homam Ahmed'},
      {num:6, name:'Boualem Khoukhi'},
      {num:7, name:'Pedro Miguel'},
      {num:8, name:'Tarek Salman'},
      {num:9, name:'Mohamed Al-Mannai'},
      {num:10, name:'Karim Boudiaf'},
      {num:11, name:'Assim Madibo'},
      {num:12, name:'Ahmed Fatehi'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Mohammed Waad'},
      {num:15, name:'Abdulaziz Hatem'},
      {num:16, name:'Hassan Al-Haydos'},
      {num:17, name:'Edmilson Junior'},
      {num:18, name:'Akram Hassan Afif'},
      {num:19, name:'Ahmed Al Ganehi'},
      {num:20, name:'Almoez Ali'},
    ]},
    { group:'I', name:'Iraq', flag:'IRQ', players:[
      {num:1,  name:'Escudo Iraq'},
      {num:2, name:'Jalal Hassan'},
      {num:3, name:'Rebin Sulaka'},
      {num:4, name:'Hussein Ali'},
      {num:5, name:'Akam Hashem'},
      {num:6, name:'Merchas Doski'},
      {num:7, name:'Zaid Tahseen'},
      {num:8, name:'Manaf Younis'},
      {num:9, name:'Zidane Iqbal'},
      {num:10, name:'Amir Al-Ammari'},
      {num:11, name:'Ibrahim Bavesh'},
      {num:12, name:'Ali Jasim'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Youssef Amyn'},
      {num:15, name:'Aimar Sher'},
      {num:16, name:'Marko Farji'},
      {num:17, name:'Osama Rashid'},
      {num:18, name:'Ali Al-Hamadi'},
      {num:19, name:'Aymen Hussein'},
      {num:20, name:'Mohanad Ali'},
    ]},
    { group:'J', name:'Jordania', flag:'JOR', players:[
      {num:1,  name:'Escudo Jordania'},
      {num:2, name:'Yazeed Abulaila'},
      {num:3, name:'Ihsan Haddad'},
      {num:4, name:'Mohammad Abu Hashish'},
      {num:5, name:'Yazan Al-Arab'},
      {num:6, name:'Abdallah Nasib'},
      {num:7, name:'Saleem Obaid'},
      {num:8, name:'Mohammad Abualnadi'},
      {num:9, name:'Ibrahim Saadeh'},
      {num:10, name:'Nizar Al-Rashdan'},
      {num:11, name:'Noor Al-Rawabdeh'},
      {num:12, name:'Mohannad Abu Taha'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Amer Jamous'},
      {num:15, name:'Musa Al-Taamari'},
      {num:16, name:'Yazan Al-Naimat'},
      {num:17, name:'Mahmoud Al-Mardi'},
      {num:18, name:'Ali Olwan'},
      {num:19, name:'Mohammad Abu Zrayq'},
      {num:20, name:'Ibrahim Sabra'},
    ]},
    { group:'K', name:'Uzbekistán', flag:'UZB', players:[
      {num:1,  name:'Escudo Uzbekistán'},
      {num:2, name:'Utkir Yusupov'},
      {num:3, name:'Farrukh Savfiev'},
      {num:4, name:'Sherzod Nasrullaev'},
      {num:5, name:'Umar Eshmurodov'},
      {num:6, name:'Husniddin Aliqulov'},
      {num:7, name:'Rustamjon Ashurmatov'},
      {num:8, name:'Khojiakbar Alijonov'},
      {num:9, name:'Abdukodir Khusanov'},
      {num:10, name:'Odiljon Hamrobekov'},
      {num:11, name:'Otabek Shukurov'},
      {num:12, name:'Jamshid Iskanderov'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Azizbek Turgunboev'},
      {num:15, name:'Khojimat Erkinov'},
      {num:16, name:'Eldor Shomurodov'},
      {num:17, name:'Oston Urunov'},
      {num:18, name:'Jaloliddin Masharipov'},
      {num:19, name:'Igor Sergeev'},
      {num:20, name:'Abbosbek Fayzullaev'},
    ]},
    { group:'D', name:'Australia', flag:'AUS', players:[
      {num:1,  name:'Escudo Australia'},
      {num:2, name:'Mathew Ryan'},
      {num:3, name:'Joe Gauci'},
      {num:4, name:'Harry Souttar'},
      {num:5, name:'Alessandro Circati'},
      {num:6, name:'Jordan Bos'},
      {num:7, name:'Aziz Behich'},
      {num:8, name:'Cameron Burgess'},
      {num:9, name:'Lewis Miller'},
      {num:10, name:'Milos Degenek'},
      {num:11, name:'Jackson Irvine'},
      {num:12, name:'Riley McGree'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Aiden O\'Neill'},
      {num:15, name:'Connor Metcalfe'},
      {num:16, name:'Patrick Yazbek'},
      {num:17, name:'Craig Goodwin'},
      {num:18, name:'Kusini Yengi'},
      {num:19, name:'Nestory Irankunda'},
      {num:20, name:'Mohamed Touré'},
    ]},
    { group:'G', name:'Nueva Zelanda', flag:'NZL', players:[
      {num:1,  name:'Escudo Nueva Zelanda'},
      {num:2, name:'Max Crocombe'},
      {num:3, name:'Alex Paulsen'},
      {num:4, name:'Michael Boxall'},
      {num:5, name:'Liberato Cacace'},
      {num:6, name:'Tim Payne'},
      {num:7, name:'Tyler Bindon'},
      {num:8, name:'Francis de Vries'},
      {num:9, name:'Finn Surman'},
      {num:10, name:'Joe Bell'},
      {num:11, name:'Sarpreet Singh'},
      {num:12, name:'Ryan Thomas'},
      {num:13, name:'Foto Grupal'},
      {num:14, name:'Matthew Garbett'},
      {num:15, name:'Marko Stamenić'},
      {num:16, name:'Ben Old'},
      {num:17, name:'Chris Wood'},
      {num:18, name:'Elijah Just'},
      {num:19, name:'Callum McCowatt'},
      {num:20, name:'Kosta Barbarouses'},
    ]},
  ]

};

function getTotalStickers() {
  let t = ALBUM_DATA.intro.items.length;
  t += ALBUM_DATA.especiales.items.length;
  t += ALBUM_DATA.cracks.items.length;
  t += ALBUM_DATA.cocacola.items.length;
  ALBUM_DATA.teams.forEach(tm => t += tm.players.length);
  return t;
}

